<template>
  <div class="container">
    <nav class="menu navbar navbar-expand-sm">
    <ul class="menu__list navbar-nav">
      <li class="menu__item nav-item ml-5">
        <n-link class="nav-link" :to="`/`">Home</n-link>
      </li>
      <li class="menu__item nav-item ml-5">
        <n-link class="nav-link" :to="`/#services`">Our Services</n-link>
      </li>
      <li class="menu__item nav-item ml-5">
        <n-link class="nav-link" :to="`/#reviews`">Portfolio</n-link>
      </li>
      <li class="menu__item nav-item ml-5">
        <n-link class="nav-link" :to="`/#faqs`">Contact</n-link>
      </li>
    </ul>
  </nav>
    <header class="header">
      <div class="header__logo">
        <n-link :to="`/`">
          <img
            src="~assets/images/candr_logo.png"
            alt="Click and Rivets logo"
          />
        </n-link>
      </div>
    </header>
    <main>
      <div id="services">
      <h2>Are you happy with your website?</h2>

      <p>Or are you paying too much and receiving too little in return? Is your website provider helping you with your online strategy? Do you have all the insight you need to understand how your customers are finding you and interacting with your site?</p>

      <h2>Your Website Should Grow Your Business</h2>

      <p>Your online presence is a vital component of your business. 93% of all website traffic is generated by Google. The first five results in a Google search get 67.60% of all the clicks (source). </p>
​
      <p>Need a new site? Want a partner to help you maximize the ROI of your online presence? We can help. Whether you just want a basic landing page or need a full featured online store we can build a site you'll love.</p>
      </div>

      <section id="about"></section>
      
      <section id="portfolio"></section>
    
      <section id="contact">
        <div class="form__container">
          <form name="contact" netlify>
            <div class="form-group mt-4">
              <label for="name" class="form-label">Name</label>
              <input
                id="name"
                type="text"
                name="name"
                class="form-control"
                required
              />
            </div>
            <div class="form-group mt-4">
              <label for="email" class="form-label">Email</label>
              <input
                id="email"
                type="email"
                name="email"
                class="form-control"
                required
              />
            </div>
            <div class="form-group mt-4">
              <label for="message" class="form-label">Message</label>
              <textarea
                id="message"
                name="message"
                class="form-control"
                rows="6"
                cols="50"
                required
              ></textarea>
            </div>

            <div class="row">
              <button class="btn btn-submit">Send</button>
            </div>
          </form>
        </div>

      </section>

    </main>
  </div>
</template>

<script>
export default {}
</script>